/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIDB;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aryan
 */
public class DBCRUD extends javax.swing.JFrame {
        
    /**
     * Creates new form DBCRUD
     */
    public DBCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(tableModel);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ROLLNO");

        jLabel2.setText("NAME");

        jLabel3.setText("AGE");

        jTextField2.setText(" ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText(" ");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:  To delete a record
        
         if(jTable1.getSelectedRow()==-1){
                JOptionPane.showMessageDialog(this, "Please select a row.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
         else{

           int con= JOptionPane.showConfirmDialog(this,"Do you want to delete this row?", "Confirm", JOptionPane.YES_NO_OPTION);
           
           //confirm by user
           if(con==JOptionPane.YES_OPTION){    
            tableModel.removeRow(jTable1.getSelectedRow());
            //DELETE db record  
            QueryUpdate("delete from CRUDTABLE where Roll_NO="+jTextField1.getText());
           
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
           }
         }
    }//GEN-LAST:event_jButton3ActionPerformed

 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: Add new row/record to Table
        if(jTextField1.getText().toString().isEmpty()||jTextField2.getText().toString().isEmpty()||jTextField3.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(this, "PLEASE FILL ALL THE FIELDS","WARNING",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
            rollNo = Integer.parseInt(jTextField1.getText()); 
            name=(String)jTextField2.getText();
            age=Integer.parseInt(jTextField3.getText());
            
            Object []newRow={rollNo,name,age};
            tableModel.addRow(newRow);
            
          //call for db 
          //TODO: DO NOT USE THUS    Query("Insert into CRUDTABLE values(?,?,?)" );
            QueryUpdate("insert into CRUDTABLE values ('"+jTextField1.getText()+"','"+jTextField2.getText()+"',"+jTextField3.getText()+")" );
            
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
     
            
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: update the table contents after selecting the content
        
          if(jTextField1.getText().toString().isEmpty()||jTextField2.getText().toString().isEmpty()||jTextField3.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(this, "PLEASE FILL ALL THE FIELDS","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
          else{
              
             rollNo = Integer.parseInt(jTextField1.getText());
             name=(String)jTextField2.getText();
             age=Integer.parseInt(jTextField3.getText());
             
              QueryUpdate(" update CRUDTABLE set NAME='" +jTextField2.getText()+ "',AGE=" +jTextField3.getText()+" where ROLL_NO="+jTextField1.getText());
              
             int row=jTable1.getSelectedRow();
              
              tableModel.setValueAt(rollNo, row, 0);
              tableModel.setValueAt(name, row, 1);
              tableModel.setValueAt(age, row, 2);
              
              jTextField1.setText(null);
              jTextField2.setText(null);
              jTextField3.setText(null);
              
              
                      
          }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here: set selected text in jtextField[s]
        
        int rowIndex= jTable1.getSelectedRow();

               rollNo=(int)tableModel.getValueAt(rowIndex,0);
               name=(String)tableModel.getValueAt(rowIndex,1);
               age=(int)tableModel.getValueAt(rowIndex,2);

               jTextField1.setText(String.valueOf(rollNo));
               jTextField2.setText(name);
               jTextField3.setText(String.valueOf(age));

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBCRUD().setVisible(true);
            }
        });
                
             
    }
     
    //TODO: custom code
    
        Object[][] data={
            {0,"Default",0}
        };
     
        String []columnName={"ROLL NO","NAME","AGE"};
        DefaultTableModel tableModel = new DefaultTableModel(data,columnName);
        
        int rollNo;
        String name;
        int age;
        
        String pass ;
        String uname;
        String url;
        Connection con=null;
        PreparedStatement st=null;
        Statement stt=null;
        
     // for Db Add 
        /** TODO: DO NOT USE THIS BLOCK
       public void Query(String qry){          
          try{
          pass ="1234";
          uname="root";
          url="jdbc:mysql://localhost:3306/dbcrud";
 
                 con= DriverManager.getConnection(url,uname,pass);
                 st=con.prepareStatement(qry);
                st.setInt(1, rollNo);
                st.setString(2,name );
                st.setInt(3,age);
                
                int count=st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Query Executed "+count+"row(s) affected"); 
           }catch( Exception e){   
              JOptionPane.showMessageDialog(this, e.getMessage());
           }          
       }
       */
        
       //for Db ADD UPDATE DELETE
       public void QueryUpdate(String qryy){
           try{
          pass ="1234";
          uname="root";
          url="jdbc:mysql://localhost:3306/dbcrud";
                con= DriverManager.getConnection(url,uname,pass);
                stt= con.createStatement();
                int count=stt.executeUpdate(qryy);
           
                JOptionPane.showMessageDialog(this, "Query Executed "+count+"row(s) affected"); 
                
                        
           }
           catch(Exception e){
              JOptionPane.showMessageDialog(this, e.getMessage()); 
           }
       }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
